[package]
name = "algorithms"
version = "0.1.0"
authors = [
    "Allister Isaiah Harvey <41553768+powpow58@users.noreply.github.com>",
]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

[dev-dependencies]
test-case = "2.0.2"
