name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Nightly build
      run: |
        rustup override set nightly
        cargo build --verbose
    - name: Run nightly tests
      run: |
        rustup override set nightly
        cargo test --verbose
